version: "3"
services:
  zomboid:
    image: project-zomboid-server:latest
    #build:
    #  context: .
    #  dockerfile: .docker/Dockerfile
    volumes:
      - "./data:/root/Zomboid"
      - "./server:/server"
    ports:
      - 16261:16261
      - 16262:16262
    env_file: .env