version: "3"
services:
  zomboid:
    #image: project-zomboid-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./data:/home/zomboid/Zomboid"
      - "./server:/home/zomboid/Server"
    ports:
      - 16261:16261/udp
      - 16262:16262/udp
    env_file: .env