version: "3"
services:
  zomboid:
    #image: project-zomboid-server:latest
    build:
      context: .
      dockerfile: Containerfile
    volumes:
      - "./server:/home/zomboid/erver"
    ports:
      - 16261:16261/udp
      - 16262:16262/udp
    env_file: .env